adminside/urls.py
from django.urls import path 
from .import views

app_name = 'adminside'

urlpatterns = [
    path('',views.dashboard , name= 'dashboard'),
    path('admin_login/',views.admin_login , name= 'admin_login'),
    path('user_mgt/',views.user_mgt , name= 'user_mgt'),
    path('admin_logout',views.admin_logout , name='admin_logout'),
    path('user_block/<int:user_id>/',views.user_block , name='user_block'),
    path('user_search',views.user_search , name='user_search'),
    path('user_block_status',views.user_block_status , name='user_block_status'),
    path('adminpage',views.adminpage, name='adminpage'),


    path('sales_report',views.sales_report , name='sales_report'),
    path('export_csv/<str:start_date>/<str:end_date>/', views.export_csv, name='export_csv'),
    path('pdf/<str:start_date>/<str:end_date>/',views.pdf , name='pdf')
]   

banner/urls.py
from django.urls import path
from .import views




urlpatterns = [
    path('banner',views.banner , name='banner'),
    path('add_banner',views.add_banner , name='add_banner'),
    path('edit_banner/<int:editbanner_id>/',views.edit_banner , name='edit_banner'),
    path('delete_banner/<int:deletebanner_id>/',views.delete_banner , name='delete_banner'),

]

cart/urls.py
from django.urls import path
from .import views



urlpatterns = [
    path('',views.cart , name="cart"),
    path('add_cart',views.add_cart , name='add_cart'),
    path('update_cart',views.update_cart , name='update_cart'),\
    path('delete_cart/<int:delete_id>/',views.delete_cart , name='delete_cart'),

]

home/urls.py
from django.urls import path
from .import views

app_name = 'home'

urlpatterns = [
    path('',views.index , name="home"),
    path('home',views.index , name="home"),
    path('about',views.about , name = "about"),
    path('shop',views.shop , name="shop"),
    path('product_details',views.product_details , name="product_details"),
    path('blog', views.blog , name= "blog"),
    path('contact', views.contact , name="contact"),    

    path('invoice/<int:invoice_id>/',views.invoice , name='invoice'),
    path('search',views.search , name='search'),
    path('filter_category',views.filter_category , name='filter_category')
]

offer/urls.py
from django.urls import path
from . import views



urlpatterns = [
    path('',views.offer, name='offer'),
    path('add_offer/', views.add_offer , name='add_offer'),
    path('delete_offer/<int:deleteoffer_id>/',views.delete_offer, name='delete_offer'),
    path('edit_offer/<int:editoffer_id>/',views.edit_offer , name='edit_offer'),


]

order/urls.py
from django.urls import path
from .import views


urlpatterns = [
    path('admin_order',views.admin_order, name='admin_order'),
    path('user_order',views.user_order , name='user_order'), 
    path('order_views/<int:orderviews_id>/',views.order_views ,name='order_views'),
    path('order_views_admin/<int:orderviews_id>/',views.order_views_admin , name='order_views_admin'),

    path('change_status',views.change_status , name='change_status'),
    path('cancel_order/<int:ordercancel_id>/',views.cancel_order , name='cancel_order'),
    path('retur_order/<int:orderreturn_id>/',views.return_order , name='return_order'),
    path('order_tracker/<int:ordertracker_id>/',views.order_tracker , name='order_tracker')

]

adminside/models.py
from django.db import models

# Create your models here.

banner/models.py
from django.db import models
from categories.models import Category
# Create your models here.

class Banner(models.Model):
    banner = models.CharField( max_length=50)
    banner_image = models.ImageField( upload_to='banner/', default='No image is available')
    caption = models.TextField()
    category_id = models.ForeignKey(Category,  on_delete=models.SET_NULL, null=True)
    is_available = models.BooleanField(default=True)

    def __str__(self) -> str:
        return self.banner

offer/forms.py
from django import forms
from .models import Offer

class OfferForm(forms.ModelForm):
    
    class Meta:
        model = Offer
        fields = ['offer_name','discount_amount', 'start_date','end_date']

adminside/views.py
from itertools import groupby
from django.shortcuts import render , redirect
from django.contrib import messages , auth
from django.contrib.auth import authenticate , login , logout
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.db.models import  Q
from django.db.models import Sum
from django.views import View
from datetime import datetime
from datetime import date
from order.models import Order , OrderCancel , OrderItem , OrderReturn
import csv 
from django.http import HttpResponse
from fpdf import FPDF

from django.db.models import Prefetch
# Create your views here.


@login_required(login_url = 'adminside:admin_login')
def dashboard(request):
    
    if request.user.is_superuser:
        orders = Order.objects.order_by('id')[:10:]
        order = Order.objects.all()


   
        sales_data  = OrderItem.objects.values('order__created_at__date').annotate(total_sale = Sum('price')).order_by('-order__created_at__date')
        categories = [item['order__created_at__date'].strftime('%d/%m') for item in sales_data]
        sales_values = [item['total_sale'] for item in sales_data]
        return_data = OrderItem.objects.filter(status__in=["Return", "Cancelled"]).values('order__created_at__date').annotate(total_returns=Sum('price')).order_by('-order__created_at__date')
        return_values = [item['total_returns'] for item in return_data]
        print(return_values)
        print(sales_values)
        try:
            total_sale= 0 
            order = Order.objects.all()
            for i in order:
                i.total_price
                total_sale += i.total_price
        except:
            total_sale = 0

        
        try:            
            total_earning = 0 
            order_ear = Order.objects.filter(od_status = 'Delivered')
            for i in order_ear:
                total_earning += i.total_price
        except:
            total_earning = 0
        try:
            status_delivery = Order.objects.filter(od_status = 'Delivered').count()
            status_return = Order.objects.filter(od_status = 'Return').count()
            status_cancel = Order.objects.filter(od_status = 'Cancelled').count()
            total = status_delivery + status_return + status_cancel
            status_delivery = (status_delivery/100)*total
            status_cancel = (status_cancel/100)*total
            status_return = (status_return/100)*total
        except:
            status_delivery = 0
            status_cancel = 0 
            status_return = 0 
            
     
        print(orders)
        print(total_sale)
        print(total_earning)
        print(status_return)
        print(status_return)
        print(sales_values)
        context = {
            'orders':orders,
            'total_sale':total_sale,
            'total_earning':total_earning,
            'total_sale':total_sale,
            'status_return':status_return,
            'status_cancel':status_cancel,
            'status_delivery':status_delivery,
            'sales_values':sales_values,
            'return_values':return_values,
            'categories':categories 
        }
        return render(request,'adminside/dashboard.html',context)
    else:       
        return redirect( 'adminside:admin_login')


def admin_login(request):
    try:
        if request.method == 'POST':
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(request , username = username , password = password)

            #validatings the fiels is empty
            if username.strip() == '' or password == '':
                messages.error(request , 'fields empty !!!')
                return redirect('adminside:admin_login')
            
            if user and user.is_superuser:
                login(request , user)
                return redirect('adminside:dashboard')
            else:
                messages.error(request ,'Invalid credentials. Please try again.')
                return redirect('adminside:admin_login')
        return render(request, 'adminside/admin_login.html')
    except Exception as e:
        print(e)
        return render(request, 'adminside/admin_login.html')


@login_required(login_url = 'adminside:admin_login')
def user_mgt(request):
    try:
        users = User.objects.all().order_by('id')
        context = {
            'users': users
        }

        return render(request, 'adminside/usermgt.html', context)
    except Exception as e:
        print(e)
        return render(request, 'adminside/usermgt.html')


@login_required(login_url='admin_login')
def admin_logout(request):
    logout(request)
    return redirect('adminside:admin_login')


@login_required(login_url='admin_login')
def user_block(request,user_id):
    try:
        # user is block 
        user = User.objects.get(id = user_id)
        if user.is_active:  
            user.is_active = False
            user.save()
        else:
            user.is_active = True
            user.save()
        return redirect('adminside:user_mgt')
    except Exception as e:
        print(e)
        return redirect('adminside:user_mgt')

@login_required(login_url='admin_login')
def user_search(request):
    try:
        search = request.POST.get('search')

        # validatings the search is empty
        if search is None or  search.strip() == '':
            messages.error(request , 'field is empty')
            return redirect('adminside:user_mgt')
        users = User.objects.filter(Q(username__icontains = search)| Q(email__icontains = search))
        context = {
            'users':users
        }
        if users:
            pass
        else:
            users : False
            messages.error(request , 'Search is not found')
            return redirect('adminside:user_mgt')
        return render(request, 'adminside/usermgt.html',context)
    except Exception as e:
        print(e)
        return render(request, 'adminside/usermgt.html')


@login_required(login_url = 'adminside:admin_login')
def user_block_status(request):
    try:
        name = request.POST.get('name')
        if name == 'Active':
            users = User.objects.filter(is_active = True)
            context = {
                'users':users
            }
            return render(request , 'adminside/usermgt.html',context)
        if name == 'Blocked':
            users = User.objects.filter(is_active = False)
            context = {
                'users':users
            }
            return render(request ,'adminside/usermgt.html',context)
        if name == 'All':
            users = User.objects.all()
            context = {
                'users':users
            }
            return render(request, 'adminside/usermgt.html',context)
    except Exception as e:
        print(e)
        return render(request,'adminside/usermgt.html')

@login_required(login_url = 'adminside:admin_login')
def adminpage(request):
    return redirect('adminside:dashboard')



@login_required(login_url = 'adminside:admin_login')
def sales_report(request):
    try:
        start_date = None
        end_date = None
        if request.method == 'POST':
            start_date = request.POST.get('start_date')
            end_date = request.POST.get('end_date')
        
            if start_date and end_date:
                start_date = datetime.strptime(start_date,'%Y-%m-%d').date()
                end_date = datetime.strptime(end_date, '%Y-%m-%d').date()
                print('start date and end date',start_date , end_date)
                if start_date > end_date:
                    messages.error(request, 'Start date must be end date')
                    return redirect('adminside:dashboard')
                if end_date > date.today():
                    messages.error(request,'End date cannot be in the future')
                    return redirect('adminside:dashboard')
                orders = Order.objects.filter(created_at__date__range=(start_date,end_date))
                print('the order is the ',orders)
                recend_order = orders.order_by('created_at')
                total_sale = sum(order.total_price for order in orders)
                total_count = orders.count()

                sales_by_status = {
                    'Pending':orders.filter(od_status = 'Pending').count(),
                    'Processing':orders.filter(od_status = 'Processing').count(),
                    'Shipped':orders.filter(od_status = 'Shipped').count(),
                    'Delivered':orders.filter(od_status = 'Delivered').count(),
                    'Cancelled':orders.filter(od_status = 'Cancelled').count(),
                    'Return':orders.filter(od_status = 'Return').count()
                    }

                sales_report = {
                    'start_date': start_date.strftime('%Y-%m-%d') if start_date else '',
                    'end_date': end_date.strftime('%Y-%m-%d') if end_date else '',
                    'total_sales': total_sale,
                    'total_orders': total_count,
                    'sales_by_status': sales_by_status,
                    'recent_orders': recend_order,
                }
                context = {
                        'sales_report':sales_report,
                }
                print('the total sale is the ',total_sale)
                return render(request,'adminside/salesreport.html',context)

        recend = Order.objects.order_by('created_at')[:10]
        orders = Order.objects.all()
        total_sale = sum(order.total_price for order in orders)
        total_count = orders.count()

        sales_by_status = {
            'Pending':orders.filter(od_status = 'Pending').count(),
            'Processing':orders.filter(od_status = 'Processing').count(),
            'Shipped':orders.filter(od_status = 'Shipped').count(),
            'Delivered':orders.filter(od_status = 'Delivered').count(),

banner/views.py
from django.shortcuts import render , redirect
from .models import Banner
from django.contrib import messages 
# Create your views here.


def banner(request):
    try:
        banner = Banner.objects.all()
        for i in banner:
            print(i.banner_image)
        context = {
            'banner':banner
        }
        return render(request,'adminside/banner.html',context)
    except Exception as e:
        print(e)
        return render(request,'adminside/banner.html')


def add_banner(request):
    try:
        if request.method == 'POST':
            banner_name = request.POST.get('banner_name')
            banner_image = request.FILES.get('banner_image')
            decs = request.POST.get('banner_discription')

            # validation 
            if banner_name.strip() =='' or decs.strip() == '':
                messages.error(request,'Field is Empty')
                return redirect('add_banner')
            if banner_image is None:
                messages.error(request,'The Image Fields is empty')
                return redirect('add_banner')
            if Banner.objects.filter(banner = banner_name).exists():
                messages.error(request,'name is already taken')
                return redirect('add_banner')
            
            banner = Banner()
            banner.banner = banner_name
            banner.banner_image = banner_image
            banner.caption = decs
            banner.save()
            messages.success(request,'Successfully Added into Banner')
            return redirect('banner')
        return redirect('banner')
    except Exception as e:
        print(e)
        return redirect('banner')

def edit_banner(request,editbanner_id):
    try:
        if request.method == 'POST':
            banner_name = request.POST.get('banner_name')
            banner_dec = request.POST.get('banner_discription')
            
            #validation
            if banner_name.strip() == '' or banner_dec.strip() == '':
                messages.error(request,'Filed is empty')
                return redirect('banner')
            if Banner.objects.filter(banner = banner_name).exists():
                messages.error(request,'name is already taken')
                return redirect('banner')
            
            banner = Banner.objects.get(id = editbanner_id)
            
            banner_image = request.FILES.get('image')
            if banner_image:
                banner.banner_image = banner_image
            else:
                messages.error(request, 'The Image Field is empty')
                return redirect('banner')
            
            banner.banner = banner_name
            banner.caption =banner_dec
            banner.save()
            messages.success(request,'Successfully edited Brand')
            return redirect('banner')
        
        return render(request,'adminside/banner.html')
    except Exception as e:
        print(e)
        return render(request, 'adminside/banner.html')


def delete_banner(request,deletebanner_id):
    try:
        banner = Banner.objects.get(id = deletebanner_id)
        banner.delete()
        messages.success(request,'Successfully Deleted')
        return redirect('banner')
    except Exception as e:
        print(e)
        return redirect('banner')

templates/adminside/salesreport.html
{% extends "adminside/adminbase.html" %}
{% load static %}
{% block dashbody %}



<div>
    <br><br>
    <h2 class="text-dark font-weight-bold" style="margin-left: 10px;"> Sales Report </h2>

    <section class="section dashboard">
        <div class="row">
            <!-- Left side columns -->
            <div class="col-lg-12">
                <div class="row">
                    <!-- Recent Sales -->
                    <div class="col-12">
                        <div class="card recent-sales overflow-auto">
                            <div class="card-body">
                                <form style="margin-left: 20%; font-size: large;" method='POST' action="{% url 'adminside:sales_report' %}">
                                    {% csrf_token %}
                                    <label for="start_date">Start Date:</label>
                                    <input type="date" id="start-date"  name='start_date'  value="{{ sales_report.start_date }}" >
                                    <label for="end_date">End Date:</label>
                                    <input type="date" id="end-date" name='end_date' value="{{ sales_report.end_date }}" >
                                    <button type="submit" class="btn btn-primary">Generate Report</button>
                                </form>

                                <div style="display: flex;  padding:5%; justify-content: space-evenly;">
                                    <h4>Total Sales: ₹ {{sales_report.total_sales}}  </h4>
                                    <h4>Total Orders: {{sales_report.total_orders}} </h4>
                                </div>
                                <h2 style="margin-left: 40%;">Sales by Status</h2>
                                <div>
                                    <ul style="display: flex;justify-content: space-evenly; font-weight: bold; margin-top: 5%; ">
                                        <li>Pending: {{sales_report.sales_by_status.Pending}} </li>
                                        <li>Processing: {{sales_report.sales_by_status.Processing}} </li>
                                        <li>Shipped: {{sales_report.sales_by_status.Shipped}}</li>
                                        <li>Delivered: {{sales_report.sales_by_status.Delivered}}</li>
                                        <li>Cancelled: {{sales_report.sales_by_status.Cancelled}}</li>
                                        <li>Return: {{sales_report.sales_by_status.Return}}</li>
                                    </ul>
                                </div>
                                <h2 style="margin-top: 5%;">{% if sales_report.start_date and sales_report.end_date %}All Orders{% else %}Recent Orders{% endif %}</h2>
                                {% if sales_report.start_date and sales_report.end_date %}
                                <a href="{% url 'adminside:export_csv' sales_report.start_date sales_report.end_date %}" class="btn btn-success">Export as CSV</a>
                                    Download CSV <i class="mdi mdi-file-excel" style="font-size: x-large;"></i>
                                  </a>
                                <a href="{% url 'adminside:pdf' sales_report.start_date sales_report.end_date %}" class="btn btn-danger" >
                                    Download PDF <i class="mdi mdi-file-pdf" style="font-size: x-large;"></i>
                                  </a>
                                  {% endif %}

                                <div class="table-responsive">
                                    <table id="example" class="display nowrap mt-5 table" style="width:100%">
                                        <thead>
                                            <tr>
                                                <th>Order ID</th>
                                                <th>Tracking Number</th>
                                                <th>Total Price</th>
                                                <th>Status</th>
                                                <th>Created At</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for i in sales_report.recent_orders %}

                                            <!-- Sample data -->
                                            <tr>
                                                <td> {{i.id}} </td>
                                                <td> {{i.tracking_no}} </td>
                                                <td>$ {{i.total_price}} </td>
                                                <td> {{i.od_status}} </td>
                                                <td> {{i.created_at}} </td>
                                            </tr>
                                            {%  endfor %}
                                        </tbody>
                                    </table>
                                </div>

                                <!-- <script>
                                    const startDate = document.getElementById("start-date");
                                    const endDate = document.getElementById("end-date");

                                    endDate.addEventListener("change", function() {
                                        if (endDate.value < startDate.value) {
                                            alert("End date cannot be before the start date.");
                                            endDate.value = '';
                                        }
                                    });
                                </script> -->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>

<script>
    setTimeout(function() {
        $('#message').fadeOut('slow');
    }, 2000);

    $(document).ready(function() {
        $('#example').DataTable({
            dom: 'Bfrtip',
            buttons: [
                'copy', 'csv', 'excel', 'pdf', 'print'
            ]
        });
    });
</script>

<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script src="https://cdn.datatables.net/1.13.4/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/buttons/2.3.6/js/dataTables.buttons.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
<script src="https://cdn.datatables.net/buttons/2.3.6/js/buttons.html5.min.js"></script>
<script src="https://cdn.datatables.net/buttons/2.3.6/js/buttons.print.min.js"></script>




{% endblock %}

templates/adminside/usermgt.html
{% extends "adminside/adminbase.html" %}
{% load static %}
{% block dashbody %}

<!-- Font Awesome -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet" />
<!-- Google Fonts -->
<link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet" />
<!-- MDB -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.4.1/mdb.min.css" rel="stylesheet" />
<style>
  .badge {
    display: inline-block;
    padding: 0.25em 0.5em;
    font-size: 0.875rem;
    font-weight: 500;
    line-height: 1;
    text-align: center;
    white-space: nowrap;
    vertical-align: middle;
    border-radius: 10rem;
  }

  .alert-success {
    color: #0ab732;
    background-color: #d4edda;
    border-color: #36ff65;
  }

  .alert-warning {
    color: #fe0000;
    background-color: #ffd3d3;
    border-color: #ffe4e4;
  }

  .alert-View {
    color: #000000;
    background-color: #cecece;
    border-color: #c2c1c1;
  }
</style>

<style>

  .button {
    display: inline-block;
    padding: 10px 20px;
    background-color: #007BFF; /* Change to your desired background color */
    color: #fff; /* Change to your desired text color */
    text-decoration: none;
    border-radius: 5px;
    border: none;
    cursor: pointer;
    font-size: 16px;
    transition: background-color 0.3s ease;
  }
  
  .button:hover {
    background-color: #0056b3; /* Change to your desired hover background color */
  }
  
</style>

<div class="container-fluid">


  <section class="content-main">

    <div class="card mb-4">
      <header class="card-header">
        <div class="row gx-3">
          <div class="col-lg-4 col-md-6 me-auto">
            <div class="input-group">
              <div class="form-outline">
              <form action="{% url 'adminside:user_search' %}" method="POST">
                {% csrf_token %}
                  <input type="search" id="form1" name="search" class="form-control" />
                  <label class="form-label" for="form1">Search</label>
                </div>
                <button type="submit" class="btn btn-primary">
                  <i class="fas fa-search"></i>
                </button>
              </form>
            </div>



          </div>
          <div class="col-lg-2 col-6 col-md-3">
            <form id="user-status-form" method="post" action="{% url 'adminside:user_block_status' %}">
              {% csrf_token %}
              <div class="col-lg-2 col-6 col-md-3">
                  <select class="form-select" name="name" id="status-select" style="width: 130px;">
                      <option value="">Status</option>
                      <option value="Blocked">Blocked</option>
                      <option value="Active">Active</option>
                      <option value="All">All</option>
                  </select>
              </div>
              <input type="hidden" name="auto_submit" value="true">
          </form>
          </div>

        </div>

        
        <div>
          <a href="{% url 'adminside:adminpage' %}" class="button">Admin Dashboard</a>
        </div>
        

      </header>
      <!-- card-header end// -->
      <div class="card-body">
        <div class="table-responsive">
          <table class="table table-hover">
            <thead>
              <tr class="text-uppercase">
                <th scope="col">id</th>
                <th scope="col">Name</th>
                <th scope="col">Email</th>
                <th scope="col">Status</th>
                <!-- <th scope="col">View</th> -->
                <th scope="col" class="text-end">Action</th>
              </tr>
            </thead>
            <tbody>
              {% for user in users %}
              <tr class="text-uppercase">
                <td style="text-align: center;">{{ user.id }}</td>
                <td><b>{{ user.username }}</td>
                <td><b>{{ user.email }}</td>

                <td>
                  {% if user.is_active %}
                  <span class="badge rounded-pill alert-success">Active</span>
                  {% else %}
                  <span class="badge rounded-pill alert-warning">Deactive</span>
                  {% endif %}
                </td>
                {% comment %} <td><a href="{% url 'user_view' user.id %}"><span
                      class="badge rounded-pill alert-View btn btn ">View</span> </a></td> {% endcomment %}
                <td class="text-end">
                  {% if user.is_active %}
                  <a href="#" class="btn btn-md rounded font-sm" data-bs-toggle="modal"
                    data-bs-target="#confirmationModal{{ user.id }}"
                    style="background-color: red; color: white;">Block</a>
                  {% else %}
                  <a href="#" class="btn btn-md rounded font-sm" data-bs-toggle="modal"
                    data-bs-target="#confirmationModal{{ user.id }}"
                    style="background-color: green; color: white;">Unblock</a>
                  {% endif %}
                </td>
              </tr>
              {% endfor %}

              <!-- Confirmation Modals -->
              {% for user in users %}
              <div class="modal fade" id="confirmationModal{{ user.id }}" tabindex="-1" role="dialog"
                aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                  <div class="modal-content">
                    <div class="modal-header">
                      {% if user.is_active %}
                      <h5 class="modal-title" id="exampleModalLabel">Confirmation Block user</h5>
                      {% else %}
                      <h5 class="modal-title" id="exampleModalLabel">Confirmation Unblock user</h5>
                      {% endif %}
                      <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                      {% if user.is_active %}

                      <h6 style="color:red">Are you sure Block this user ?</h6>
                      {% else %}
                      <h6 style="color:rgb(7, 194, 29)">Are you sure Unblock this user ?</h6>
                      {% endif %}
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                      <a href="{% url 'adminside:user_block' user.id %}">
                        <button type="button" class="btn btn-primary">Confirm</button>
                      </a>
                    </div>
                  </div>
                </div>
              </div>
            

              {% endfor %}      
              <script>
                document.addEventListener('DOMContentLoaded', function () {
                    const statusSelect = document.getElementById('status-select');
                    
                    statusSelect.addEventListener('change', function () {
                        document.getElementById('user-status-form').submit();
                    });
                });
            </script>


{% endblock  %}