cart/urls.py
from django.urls import path
from .import views



urlpatterns = [
    path('',views.cart , name="cart"),
    path('add_cart',views.add_cart , name='add_cart'),
    path('update_cart',views.update_cart , name='update_cart'),\
    path('delete_cart/<int:delete_id>/',views.delete_cart , name='delete_cart'),

]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path('user/',include('userauth.urls')),
    path('adminside/',include('adminside.urls')),
    path('categories/',include('categories.urls')),
    path('product/',include('product.urls')),
    path('cart/',include('cart.urls')),
    path('userprofile',include('userprofile.urls')),
    path('order/',include('order.urls')),
    path('checkout/',include('checkout.urls')),
    path('coupon/',include('coupon.urls')),
    path('wishlist/',include('wishlist.urls')),
    path('offer/',include('offer.urls')),
    path('banner/',include('banner.urls')),
   

] +static(settings. MEDIA_URL,document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from .import views

app_name = 'home'

urlpatterns = [
    path('',views.index , name="home"),
    path('home',views.index , name="home"),
    path('about',views.about , name = "about"),
    path('shop',views.shop , name="shop"),
    path('product_details',views.product_details , name="product_details"),
    path('blog', views.blog , name= "blog"),
    path('contact', views.contact , name="contact"),    

    path('invoice/<int:invoice_id>/',views.invoice , name='invoice'),
    path('search',views.search , name='search'),
    path('filter_category',views.filter_category , name='filter_category')
]

userauth/urls.py
from django.urls import path
from .import views

app_name = 'userauth'

urlpatterns = [
    path('user_login/',views.user_login, name="user_login"),
    path('register/',views.register_views, name="register"),
    path('logout/',views.user_logout, name='user_logout'),

    path('forget_password',views.forget_password , name='forget_password'),
    path('change_password/<str:token>',views.change_password, name='change_password')
]

templates/base.html
{% load static %}
<!doctype html>
<html class="no-js" lang="zxx">
<head>


    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Watch shop | eCommers</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="manifest" href="site.webmanifest">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'user/assets/user/img/favicon.ico' %}">

    <!-- CSS here -->
    <link rel="stylesheet" href="{% static 'user/assets/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'user/assets/css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'user/assets/css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'user/assets/css/slicknav.css' %}">
    <link rel="stylesheet" href="{% static 'user/assets/css/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'user/assets/css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'user/assets/css/fontawesome-all.min.css' %}">
    <link rel="stylesheet" href="{% static 'user/assets/css/themify-icons.css' %}">
    <link rel="stylesheet" href="{% static 'user/assets/css/slick.css' %}">
    <link rel="stylesheet" href="{% static 'user/assets/css/nice-select.css' %}">
    <link rel="stylesheet" href="{% static 'user/assets/css/style.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">    
    <link href="https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@300;400;600;700;800;900&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.theme.default.min.css">

  

</head>
</head>


<style>
    a, a:hover {
        text-decoration: none;
    }
</style>
<body>
    <!--? Preloader Start -->
    <div id="preloader-active"> 
        <div class="preloader d-flex align-items-center justify-content-center">
            <div class="preloader-inner position-relative">
                <div class="preloader-circle"></div>
                <div class="preloader-img pere-text">
                    <img src="{% static 'user/assets/user/img/logo/logo.png' %}" alt="">
                </div>
            </div>
        </div>
    </div>
    <!-- Preloader Start -->
    <header>
        <!-- Header Start -->
        <div class="header-area">
            <div class="main-header header-sticky">
                <div class="container-fluid">
                    <div class="menu-wrapper">
                        <!-- Logo -->
                        <div class="logo">
                            <a href="index.html"><img src="{% static 'user/assets/img/logo/logo.png' %}" alt=""></a>
                        </div>
                        <!-- Main-menu -->
                        <div class="main-menu d-none d-lg-block">
                            <nav>                                                
                                <ul id="navigation">  
                                    <li><a href="{% url 'home:home' %}">Home</a></li>
                                    <li><a href="{% url 'home:shop' %}">shop</a></li>
                                    <li><a href="{% url 'cart' %}">Cart</a></li>
                                    </li>
                                    </li>
                                    {% if user.is_authenticated %}
                                    <li><a href="{% url 'userauth:user_logout' %}">Logout</a>
                                            {% else %}
                                            <li><a href="{% url 'userauth:user_login' %}">Login</a></li>
                                            <li><a href="{% url 'userauth:register' %}">Regisration</a></li>
                                            {% endif %}                                            
                                        </ul>
                                    </li>
                                </ul>
                            </nav>
                        </div>

                                                <!-- Header Right -->
                                                <div class="header-right">
                                                    <ul>
                                                        <li>
                                                         

                                                        </li>
                                                        
                                                        {% if user.is_authenticated%}
                                                            <li> <a href="{% url 'userprofile' %}"><span class="flaticon-user"></span></a></li>
                                                        {% else %}
                                                            <li> <a href="{% url 'userauth:user_login' %}"><span class="flaticon-user"></span></a></li>
                                                        {% endif  %}
                                                        <li><a href="{% url 'cart' %}"><span class="flaticon-shopping-cart"></span></a> </li>
                                                    </ul>
                                                </div>
                                            </div>
                                            <!-- Mobile Menu -->
                                            <div class="col-12">
                                                <div class="mobile_menu d-block d-lg-none"></div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- Header End -->
                            </header>
                        
 {% block content  %}
 
 {% endblock content %}





<!-- JS here -->

<script src="{% static './user/assets/js/vendor/modernizr-3.5.0.min.js' %}"></script>
<!-- Jquery, Popper, Bootstrap -->
<script src=" {% static './user/assets/js/vendor/jquery-1.12.4.min.js' %}"></script>
<script src="{% static './user/assets/js/popper.min.js' %}"></script>
<script src="{% static './user/assets/js/bootstrap.min.js' %}"></script>
<!-- Jquery Mobile Menu -->
<script src="{% static './user/assets/js/jquery.slicknav.min.js' %}"></script>

<!-- Jquery Slick , Owl-Carousel Plugins -->
<script src="{% static './user/assets/js/owl.carousel.min.js' %}"></script>
<script src="{% static './user/assets/js/slick.min.js' %}"></script>

<!-- One Page, Animated-HeadLin -->
<script src="{% static './user/assets/js/wow.min.js' %}"></script>
<script src="{% static './user/assets/js/animated.headline.js' %}"></script>
<script src="{% static './user/assets/js/jquery.magnific-popup.js' %}"></script>

<!-- Scrollup, nice-select, sticky -->
<script src="{% static './user/assets/js/jquery.scrollUp.min.js' %}"></script>
<script src="{% static './user/assets/js/jquery.nice-select.min.js' %}"></script>
<script src="{% static './user/assets/js/jquery.sticky.js' %}"></script>

<!-- contact js -->
<script src="{% static './user/assets/js/contact.js' %}"></script>
<script src="{% static './user/assets/js/jquery.form.js' %}"></script>
<script src="{% static './user/assets/js/jquery.validate.min.js' %}"></script>
<script src="{% static './user/assets/js/mail-script.js' %}"></script>
<script src="{% static './user/assets/js/jquery.ajaxchimp.min.js' %}"></script>

<!-- Jquery Plugins, main Jquery -->	
<script src="{% static './user/assets/js/plugins.js' %}"></script>
<script src="{% static './user/assets/js/main.js' %}"></script>

<!-- Jquery Razor pay for checkout  -->
<script src="{% static './user/assets/js/checkout.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js"></script>



</body>
</html>