cart/urls.py
from django.urls import path
from .import views



urlpatterns = [
    path('',views.cart , name="cart"),
    path('add_cart',views.add_cart , name='add_cart'),
    path('update_cart',views.update_cart , name='update_cart'),\
    path('delete_cart/<int:delete_id>/',views.delete_cart , name='delete_cart'),

]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path('user/',include('userauth.urls')),
    path('adminside/',include('adminside.urls')),
    path('categories/',include('categories.urls')),
    path('product/',include('product.urls')),
    path('cart/',include('cart.urls')),
    path('userprofile',include('userprofile.urls')),
    path('order/',include('order.urls')),
    path('checkout/',include('checkout.urls')),
    path('coupon/',include('coupon.urls')),
    path('wishlist/',include('wishlist.urls')),
    path('offer/',include('offer.urls')),
    path('banner/',include('banner.urls')),
   

] +static(settings. MEDIA_URL,document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from .import views

app_name = 'home'

urlpatterns = [
    path('',views.index , name="home"),
    path('home',views.index , name="home"),
    path('about',views.about , name = "about"),
    path('shop',views.shop , name="shop"),
    path('product_details',views.product_details , name="product_details"),
    path('blog', views.blog , name= "blog"),
    path('contact', views.contact , name="contact"),    

    path('invoice/<int:invoice_id>/',views.invoice , name='invoice'),
    path('search',views.search , name='search'),
    path('filter_category',views.filter_category , name='filter_category')
]

userauth/urls.py
from django.urls import path
from .import views

app_name = 'userauth'

urlpatterns = [
    path('user_login/',views.user_login, name="user_login"),
    path('register/',views.register_views, name="register"),
    path('logout/',views.user_logout, name='user_logout'),

    path('forget_password',views.forget_password , name='forget_password'),
    path('change_password/<str:token>',views.change_password, name='change_password')
]

userprofile/urls.py
from django.urls import path
from .import views



urlpatterns = [
    path('',views.userprofile , name='userprofile'),
    path('add_address',views.add_address, name='add_address'),
    path('edit_profile',views.edit_profile, name='edit_profile'),
    path('changepassword',views.changepassword , name='changepassword'),
    path('edit_address/<int:editaddress_id>/',views.edit_address , name='edit_address'),
    path('delete_address/<int:deleteaddress_id>/',views.delete_address , name='delete_address'),
    path('edit_image',views.edit_image , name='edit_image'),
    

    path('wallet',views.wallet , name='wallet' ),
    path('chatbox',views.chat_box, name='chatbox')

]   

userprofile/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Address(models.Model):
    user = models.ForeignKey(User , on_delete=models.CASCADE)
    first_name = models.CharField( max_length=50,blank=True)
    last_name = models.CharField( max_length=50,blank=True)
    phone = models.CharField(blank=True, max_length=50)
    email = models.EmailField( max_length=254,blank=True)
    address = models.CharField( max_length=50,blank=True)
    country = models.CharField( max_length=50,blank=True)
    state = models.CharField( max_length=50,blank=True)
    city = models.CharField( max_length=50,blank=True)
    pincode = models.CharField( max_length=50,blank=True)
    order_note = models.CharField( max_length=50,null=True, default='')
    is_available = models.BooleanField(null=True,blank=True,default=True)
    image = models.ImageField( upload_to='userprofile',null=True,blank=True, height_field=None, width_field=None, max_length=None)

    def __str__(self) -> str:
        return f"{self.id}"
    


class Wallet(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    wallet = models.PositiveIntegerField(default=0)


class Transaction(models.Model):
    wallet = models.ForeignKey(Wallet, on_delete=models.CASCADE,null=True)
    RAZORPAY = 'Razorpay'
    COD = 'COD'
    WALLET = 'Wallet'
    TRANSACTION_METHOD_CHOICES = [
        (RAZORPAY, 'Razorpay'),
        (COD, 'Cash on Delivery'),
        (WALLET, 'Wallet')  
    ]
    CANCEL_ORDER = 'Cancel Order'
    RETURN_ORDER = 'Return Order'
    TRANSACTION_REASONS = [
        (CANCEL_ORDER, 'Cancel Order'),
        (RETURN_ORDER, 'Return Order'),
    ]
    reason = models.CharField(max_length=20, choices=TRANSACTION_REASONS,null=True)
    payment_method = models.CharField( max_length=50,choices=TRANSACTION_METHOD_CHOICES, null=True)
    amount = models.DecimalField(max_digits=10, decimal_places=2,null=True)    
    description = models.TextField(null=True, blank=True)
    timestamp = models.DateTimeField(auto_now_add=True)

userprofile/views.py
from django.shortcuts import render , redirect
from .import views
from django.core.exceptions import ObjectDoesNotExist
from .models import Address , Wallet , Transaction
from django.contrib.auth.models import User
from django.contrib import messages 
from django.contrib.auth.hashers import check_password
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth import authenticate
from userauth.models import Customer
import re
from django.core.validators import validate_email
from django.forms import ValidationError
# Create your views here.

def userprofile(request):
    try:
        wallet = 0
        try:
            wallet = Wallet.objects.filter(user = request.user).first()

        except Wallet.DoesNotExist:
            wallet = 0
        
        try:
            user = Customer.objects.get(id = request.user.id)
        except Customer.DoesNotExist:
            user = None
        user_auth = User.objects.get(id = request.user.id)


        context = {
            'address': Address.objects.filter(user=request.user,is_available=True),
            'wallet':wallet,
            'user':user,
            'user_auth':user_auth
            
            }
        return render(request , 'user/userprofile.html' , context)
    except Exception as e:
        print(e)
        return render(request, 'user/userprofile.html')


def add_address(request):
    try:
        if request.method == 'POST':
            firstname = request.POST.get('firstname')
            lastname = request.POST.get('lastname')
            number = request.POST.get('phone')
            email = request.POST.get('email')
            address_user = request.POST.get('address')
            country = request.POST.get('country')
            state = request.POST.get('state')
            city = request.POST.get('city')
            pincode = request.POST.get('pincode')
            order_note = request.POST.get('order_note')

        

            # validatings fields is empty
            if not request.user.is_authenticated:
                messages.error(request, 'User field must be login')
                return redirect('userprofile')

            if firstname.strip() == '':
                messages.error(request , 'First name fiels is empty')
                return redirect('userprofile')
            if lastname.strip() == '':  
                messages.error(request ,'Last name is empty')
                return redirect('userprofile')
            if number.strip() == '':
                messages.error(request, 'Number feilds is empty')
                return redirect('userprofile')
            if not re.search(re.compile(r'(\+91)?(-)?\s*?(91)?\s*?(\d{3})-?\s*?(\d{3})-?\s*?(\d{4})'),number):
                messages.error(request,'Enter valid phone number')
                return redirect('userprofile')
            phonenumber_checkings = len(number)
            if not phonenumber_checkings == 10:
                messages.error(request, 'Phone Number should be 10 digits')
                return redirect('userprofile')
            
            if email.strip() == '':
                messages.error(request, 'Email feild is empty')
                return redirect('userprofile')
            
            email_check = validator_email(email)
            if email_check is False:
                messages.error(request, 'Email is not valid')
                return redirect('userprofile')
            
            if address_user.strip() == '':
                messages.error(request , 'Address feilds is empty')
                return redirect('userprofile')
            if country.strip() == '':
                messages.error(request, 'Country feild is empty')
                return redirect('userprofile')
            if state.strip() == '':
                messages.error(request , 'State feild is empty')
                return redirect('userprofile')
            if city.strip() == '':
                messages.error(request, 'City feilds is empty')
                return redirect('userprofile')
            if pincode.strip() == '':
                messages.error(request , 'Pincode is empty')
                return redirect('userprofile')
            if not re.search(re.compile(r'^\d{6}$'),pincode):
                messages.error(request,'Should only 6 contain numeric')
                return redirect('userprofile')
            
            #creatings address
            address_item = Address.objects.create(
                user = request.user,
                first_name = firstname,
                last_name = lastname,
                email = email,
                phone = number,
                address = address_user,
                country = country,
                state = state,
                city = city,
                pincode = pincode,
                order_note = order_note,
            )
            address_item.save()
            messages.success(request, 'Succesffully added')
            return redirect('userprofile')
        return redirect('userprofile')
    except Exception as e:
        print(e)
        return redirect('userprofile')

   

def edit_address(request,editaddress_id):
    try:
        if request.method == 'POST':
            firstname = request.POST.get('firstname')
            lastname = request.POST.get('lastname')
            number = request.POST.get('phone')
            email = request.POST.get('email')
            address = request.POST.get('address')
            country = request.POST.get('country')
            state = request.POST.get('state')
            city = request.POST.get('city')
            pincode = request.POST.get('pincode')
            order_note = request.POST.get('order_note')

            # validatings the fields is empty
            if request.user is None:
                messages.error(request, 'User field must be login')
                return redirect('userprofile')

            if firstname.strip() == '':
                messages.error(request , 'First name fiels is empty')
                return redirect('userprofile')
            if lastname.strip() == '':  
                messages.error(request ,'Last name is empty')
                return redirect('userprofile')
            
            if number.strip() == '':
                messages.error(request, 'Number feilds is empty')
                return redirect('userprofile')
            if not re.search(re.compile(r'(\+91)?(-)?\s*?(91)?\s*?(\d{3})-?\s*?(\d{3})-?\s*?(\d{4})'),number):
                messages.error(request,'Enter valid phone number')
                return redirect('userprofile')
            phonenumber_checkings = len(number)
            if not phonenumber_checkings == 10:
                messages.error(request, 'Phone Number should be 10 digits')
                return redirect('userprofile')
            
            if email.strip() == '':
                messages.error(request, 'Email feild is empty')
                return redirect('userprofile')
                    
            email_check = validator_email(email)
            if email_check is False:
                messages.error(request, 'Email is not valid')
                return redirect('userprofile')
            
            if address.strip() == '':
                messages.error(request , 'Address feilds is empty')
                return redirect('userprofile')
            if country.strip() == '':
                messages.error(request, 'Country feild is empty')
                return redirect('userprofile')
            if state.strip() == '':
                messages.error(request , 'State feild is empty')
                return redirect('userprofile')
            if city.strip() == '':
                messages.error(request, 'City feilds is empty')
                return redirect('userprofile')
            if pincode.strip() == '':
                messages.error(request , 'Pincode is empty')
                return redirect('userprofile')
            
            if not re.search(re.compile(r'^\d{6}$'),pincode):
                messages.error(request,'Should only 6 contain numeric')
                return redirect('userprofile')
            


            #Editings the address
            address = Address.objects.get(id = editaddress_id)

            address.first_name = firstname
            address.last_name = lastname
            address.phone = number
            address.email = email
            address.country = country
            address.state = state
            address.city = city
            address.pincode = pincode
            address.order_note = order_note
            address.save()
            return redirect('userprofile')
        else:
            return redirect('userprofile')
    except Exception as e:
        print(e)
        return redirect('userprofile')




def edit_profile(request):
    try:
        if request.method == 'POST':
            username = request.POST.get('username')
            email = request.POST['email']

            # validatings the fields is empty
            if username.strip() == '':
                messages.error(request , 'Username feilds is empty')
                return redirect('userprofile')
            if email.strip() == '':
                messages.error(request , 'Email fields is empty')
                return redirect('userprofile')
            try:

                #Editings the updated
                user = User.objects.get(username = request.user)
                user.username = username
                user.email = email
                user.save()
                messages.success(request, 'UserProfile Updated Successfully')
            except ObjectDoesNotExist:
                messages.error(request , 'User does not exist')
        return redirect('userprofile')
    except Exception as e:
        print(e)
        return redirect('userprofile')
        

def changepassword(request):
    try:
        if request.method == 'POST':

templates/user/chat.html
{% extends "base.html" %} 
{% load static %} 
{% block content %}

<style>


    .chatbox {
        width: 300px;
        max-width: 90%;  /* to ensure it doesn't get too wide on smaller screens */
    }
    
    
    .chatbox-header {
        padding: 10px 15px;
        background-color: #007BFF;
        color: white;
        display: flex;
        justify-content: space-between;
        align-items: center;
        cursor: pointer;
    }
    
    .chatbox-toggle {
        font-size: 18px;
    }
    
    .chatbox-body {
        flex: 1;
        overflow-y: auto;
        padding: 10px 15px;
        background-color: #f6f6f6;
    }
    
    .message {
        margin-bottom: 10px;
        padding: 10px;
        border-radius: 8px;
    }
    
    .sender {
        background-color: #007BFF;
        color: white;
        align-self: flex-start;
    }
    
    .receiver {
        background-color: #e5e5e5;
        align-self: flex-end;
    }
    
    .chatbox-footer {
        display: flex;
        align-items: center;
        padding: 5px 10px;
        background-color: #ffffff;
        border-top: 1px solid #eee;
    }
    
    .chatbox-footer input {
        flex: 1;
        padding: 10px;
        margin-right: 10px;
        border: 1px solid #ddd;
        border-radius: 5px;
    }
    
    .chatbox-footer button {
        padding: 8px 15px;
        border: none;
        background-color: #007BFF;
        color: white;
        cursor: pointer;
        border-radius: 5px;
        transition: background-color 0.3s;
    }
    
    .chatbox-footer button:hover {
        background-color: #0056b3;
    }
  
    
</style>

    <div class="chatbox" style="top: 50%; left:50%">
        <div class="chatbox-header">
            Customer Support
            <span class="chatbox-toggle">-</span>
        </div>
        <div class="chatbox-body">
            <div class="message sender">Hello! How can I help you today?</div>
            <!-- User messages and other messages will go here -->
        </div>
        <div class="chatbox-footer">
            <input type="text" id="text" placeholder="Type a message..." />
            <button>Send</button>
        </div>
    </div>
    

    <script>
        function getUserResponse(){
            var userinput = $('#text').val();
            
        }
    </script>


{% endblock content  %}

templates/user/login.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<style>
    #usernameFeedback ,#passwordFeedback {
        color: red;
    }
</style>
    <main>
        <!-- Hero Area Start--> 
        <div class="slider-area ">
            <div class="single-slider slider-height2 d-flex align-items-center">
                <div class="container">
                    <div class="row">
                        <div class="col-xl-12">
                            <div class="hero-cap text-center">
                                <h2>Login</h2>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Hero Area End-->
        <!--================login_part Area =================-->

  

        <section class="login_part section_padding">
            <div class="container">
                <div class="row align-items-center">
                    <!-- Left Side: New to our Shop? -->
                    <div class="col-lg-6 col-md-6">
                        <div class="login_part_text text-center">
                            <div class="login_part_text_iner">
                                <h2>New to our Shop?</h2>
                                <p>There are advances being made in science and technology everyday, and a good example of this is the</p>
                                <a href="{% url 'userauth:register' %}" class="btn_3">Create an Account</a>
                            </div>
                        </div>
                    </div>
                    <!-- Right Side: Login Form -->
                    <div class="col-lg-6 col-md-6">
                        <div class="login_part_form">
                            <div class="login_part_form_iner">
                                <h3>Welcome Back ! <br>
                                    Please Sign in now</h3>
                                <form class="row contact_form" action="{% url 'userauth:user_login' %}" method="post" novalidate="novalidate">
                                    {% csrf_token %}
                                    <div class="col-md-12 form-group p_star">
                                        <input type="text" class="form-control" id="username" name="username" value="" placeholder="Username" pattern="[a-zA-Z0-9]{5,15}" title="Username must be alphanumeric and between 5-15 characters">
                                        <span id="usernameFeedback"></span>
                                    </div>
                                    <div class="col-md-12 form-group p_star">
                                        <input type="password" class="form-control" id="password" name="password" value="" placeholder="Password" pattern="(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{8,}" title="Must contain at least one number and one uppercase and lowercase letter, and at least 8 or more characters">
                                        <span id="passwordFeedback"></span>
                                    </div>
                                    <div class="col-md-12 form-group">
                                        <div class="creat_account d-flex align-items-center">
                                            <input type="checkbox" id="f-option" name="selector">
                                            <label for="f-option">Remember me</label>
                                        </div>
                                        <button type="submit" value="submit" class="btn_3">log in</button>
                                        <a class="lost_pass" href="{% url 'userauth:forget_password' %}">forget password?</a>
                                    </div>
                                    
                                    {% if messages %}
                                    <div class="message-container">
                                        {% for message in messages %}
                                          <div class="message" style="background-color: #ffcccc; border: 1px solid #ccc; padding: 10px; margin-bottom: 10px; border-radius: 5px;">
                                            <button type="button" class="close" data-dismiss="alert" aria-label="Close" style="float: right;">
                                              <span aria-hidden="true">&times;</span>
                                            </button>
                                            <i class="{{ message.level_icon }}" style="margin-right: 5px;"></i>
                                            <p style="margin: 0;">{{ message }}</p>
                                          </div>
                                        {% endfor %}
                                      </div>
                                      {% endif  %}

                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            

        </section>
        


        <!--================login_part end =================-->
    </main>


    <script>
        document.addEventListener('DOMContentLoaded', function() {
          function setupValidation(inputId, feedbackId) {
            console.log('calling this function')
            const inputElem = document.getElementById(inputId);
            const feedbackElem = document.getElementById(feedbackId);
        
            inputElem.addEventListener('input', function() {
                if (inputElem.validity.patternMismatch) {
                    feedbackElem.textContent = inputElem.title;
                } else {
                    feedbackElem.textContent = ''; // Clear the error message if input matches the pattern
                }
            });
        }
        
        // Set up validation for each input
        setupValidation('username', 'usernameFeedback');
        setupValidation('password', 'passwordFeedback');
   
          
      });
       
      
      </script>
      
{% endblock content %}

templates/user/register.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<style>
  #usernameFeedback,#emailFeedback,#genderFeedback , #passwordFeedback{
    color: red;
  }
</style>

{% if otp %}
<section class="login_part padding_top">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-6 col-md-6">
                <form class="row contact_form" action="{% url 'userauth:register' %}"method="POST" novalidate="novalidate">
                    {% csrf_token %}
                    <h3>Enter yor otp here</h3>
                    <div class="col-md-12 form-group p_star">
                        <input type="text" class="form-control" id="otp" name="otp">
                        <input type="hidden" class="form-control" id="otp" name="otp1">
                    </div>
                    <input type="hidden" value="{{ user.email }}" name="email">
                    <input type="hidden" value="{{ user.email }}" name="user1">
                    <div class="col-md-12 form-group">
                        <button type="submit" class="btn_3">Submit</button>
                        <a class="lost_pass" href="#">Forgot password?</a>
                    </div>
                    {% for message in messages %}
                    <div class="message text-center {% if message.tags %}{{ message.tags }}{% endif %}">
                        {{ message }}
                    </div>
                    {% endfor %}
                </form>
            </div>
        </div>
    </div>
</section>
{% else %}




    <main>
        <!-- Hero Area Start-->
        <div class="slider-area ">
            <div class="single-slider slider-height2 d-flex align-items-center">
                <div class="container">
                    <div class="row">
                        <div class="col-xl-12">
                            <div class="hero-cap text-center">
                                <h2>Regisration</h2>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Hero Area End-->
      <!--================login_part Area =================-->
        <section class="vh-100 bg-image">

        <div class="mask d-flex align-items-center h-100 gradient-custom-3">
          <div class="container h-100">
            <div class="row d-flex justify-content-center align-items-center h-100">
              <div class="col-12 col-md-9 col-lg-7 col-xl-6">
                <div class="card" style="border-radius: 15px;">
                  <div class="card-body p-5">
                    <h2 class="text-uppercase text-center mb-5">Create an account</h2>
    
                    <form method="post" action="{% url 'userauth:register' %}">
                      {% csrf_token %}

                      <div class="form-outline mb-4">
                        <label class="form-label" for="username">Username</label>
                        <input type="text" id="username" class="form-control form-control-lg" name="username" pattern="[a-zA-Z0-9]{5,15}" title="Username must be alphanumeric and between 5-15 characters"  />
                        <span id="usernameFeedback"></span>
                      </div>
                    
                      <div class="form-outline mb-4">
                        <label class="form-label" for="email">Email</label>
                        <input type="email" id="email" class="form-control form-control-lg" name="email" pattern="[a-z0-9._%+\-]+@[a-z0-9.\-]+\.[a-z]{2,}$" title="Please enter a valid email address" />
                        <span id="emailFeedback"></span>
                      </div>

                      <div class="form-outline mb-4">
                        <label class="form-label" for="email">Gender</label>
                        <input type="text" id="gender" class="form-control form-control-lg" name="gender"  pattern="male|female|other" title="Please enter 'male', 'female', or 'other'" />
                        <span id="genderFeedback"></span>
                      </div>
      

                      <div class="form-outline mb-4">
                        <label class="form-label" for="password1">Password</label>
                        <input type="password" id="password1" class="form-control form-control-lg" name="password1" pattern="(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{8,}"  title="Must contain at least one  number and one uppercase and lowercase letter, and at least 8 or more characters"  />
                        <span id="passwordFeedback"></span>
                      </div>
                    
                      <div class="form-outline mb-4">
                        <label class="form-label" for="password2">Confirm Password</label>
                        <input type="password" id="password2" class="form-control form-control-lg" name="password2" title="Password must match the one above." />
                      </div>

                      <div class="form-outline mb-4">
                        <label class="form-label" for="password2">Referal Offer</label>
                        <input type="mixed" placeholder="Not compulsary" id="referal_offer" class="form-control form-control-lg" name="referal_offer"  />
                      </div>
                    
                      <!-- Message Container for Error Messages -->
                      <div class="message-container">
                        {% for message in messages %}
                          <div class="message" style="background-color: #ffcccc; border: 1px solid #ccc; padding: 10px; margin-bottom: 10px; border-radius: 5px;">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close" style="float: right;">
                              <span aria-hidden="true">&times;</span>
                            </button>
                            <i class="{{ message.level_icon }}" style="margin-right: 5px;"></i>
                            <p style="margin: 0;">{{ message }}</p>
                          </div>
                        {% endfor %}
                      </div>
                    
                      <!-- Submit Button -->
                      <div class="d-flex justify-content-center">
                        <button type="submit" class="btn btn-success btn-block btn-lg gradient-custom-4 text-body">Register</button>
                      </div>
                    
                      <!-- Login Link -->
                      <p class="text-center text-muted mt-5 mb-0">Already have an account? <a href="{% url 'userauth:user_login' %}" class="fw-bold text-body"><u>Login here</u></a></p>
                    </form>
                    
      
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    </main> 
{% endif %}


<script>
  document.addEventListener('DOMContentLoaded', function() {
    function setupValidation(inputId, feedbackId) {
      console.log('calling this function')
      const inputElem = document.getElementById(inputId);
      const feedbackElem = document.getElementById(feedbackId);
  
      inputElem.addEventListener('input', function() {
          if (inputElem.validity.patternMismatch) {
              feedbackElem.textContent = inputElem.title;
          } else {
              feedbackElem.textContent = ''; // Clear the error message if input matches the pattern
          }
      });
  }
  
  // Set up validation for each input
  setupValidation('username', 'usernameFeedback');
  setupValidation('email', 'emailFeedback');
  setupValidation('gender', 'genderFeedback');
  setupValidation('password1', 'passwordFeedback');
    
});
 

</script>

{% endblock content %}